# -*- coding: utf-8 -*-
"""썸네일지정_완료.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-N2lFVDJ4CSMz1G_LfSh6cwSVfjw6Y0Y
"""

#@title 1. 라이브러리 설치 (첫 1회만 실행)
# [수정] 라이브러리 충돌 해결 (protobuf 버전 4.x로 강제 다운그레이드)
!pip install --upgrade --force-reinstall google-cloud-vision opencv-python-headless "protobuf<5.0.0"

#@title 2. Google Cloud 인증
# (Cloud Vision API가 활성화된 Google 계정으로 인증하세요)
from google.colab import auth
print("Google Cloud 계정으로 인증을 진행합니다...")
auth.authenticate_user()
print("인증 완료!")

#@title 3. [신규] Google Drive 마운트
# (테스트용 영상을 Drive에서 불러오기 위해 필요합니다)
from google.colab import drive
import os
drive.mount('/content/drive')
print("\n✅ Google Drive가 '/content/drive'에 마운트되었습니다.")
print("다음 셀에서 테스트할 영상 파일의 경로를 확인해주세요.")

#@title 4. 백엔드 AI 분석 파이프라인 (최적 썸네일 생성)

from google.cloud import vision
import cv2
import os
import numpy as np # numpy 임포트
from google.colab.patches import cv2_imshow
import math

# Google Cloud 프로젝트 ID 설정
PROJECT_ID = "braided-liberty-476215-v4"

# --- 1. Vision AI 클라이언트 초기화 ---
try:
    client_options = {"quota_project_id": PROJECT_ID}
    vision_client = vision.ImageAnnotatorClient(client_options=client_options)
    print(f"✅ Vision AI 클라이언트가 '{PROJECT_ID}' 프로젝트로 초기화되었습니다.")
except Exception as e:
    print(f"❌ Vision AI 클라이언트 초기화 오류: {e}")

# --- 2. 1초 간격 프레임 추출 함수 ---
def extract_frames_by_interval(video_path, sec_per_frame=1.0):
    """
    비디오 파일에서 설정된 시간(초) 간격으로 프레임을 추출합니다.
    """
    print(f"\n'{video_path}'에서 {sec_per_frame}초 간격으로 프레임 추출 중...")
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"오류: 비디오 파일을 열 수 없습니다: {video_path}")
        return []

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_interval = int(fps * sec_per_frame)
    if frame_interval == 0: frame_interval = 1

    frames_data = []
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if frame_count % frame_interval == 0:
            ret_enc, buffer = cv2.imencode('.jpg', frame)
            if ret_enc:
                current_time_sec = frame_count / fps
                frames_data.append({
                    'time_sec': current_time_sec,
                    'image_bytes': buffer.tobytes(),
                    'image_cv2': frame # 시각적 확인을 위해 cv2 이미지도 저장
                })

        frame_count += 1

    cap.release()
    print(f"✅ 총 {len(frames_data)}개의 프레임이 추출되었습니다.")
    return frames_data

# --- 3. [신규] Vision AI 얼굴 분석 및 점수화 함수 ---
# Vision AI가 반환하는 Likelihood 문자열을 점수로 변환
LIKELIHOOD_SCORE = {
    'UNKNOWN': 0,
    'VERY_UNLIKELY': 0,
    'UNLIKELY': 1,
    'POSSIBLE': 2,
    'LIKELY': 4,
    'VERY_LIKELY': 5
}
# [삭제] LIKELIHOOD_STRING (디버깅용) 삭제


def analyze_frame_for_thumbnail(image_bytes):
    """
    이미지 바이트를 Vision AI로 전송하여 얼굴을 분석하고 썸네일 점수를 매깁니다.
    """
    image = vision.Image(content=image_bytes)

    response = vision_client.face_detection(image=image)
    faces = response.face_annotations

    if not faces:
        return 0, "얼굴 없음", "N/A" # 점수, 상태, mouth_info

    best_face_score = -999
    best_mouth_info = "N/A"

    for face in faces:
        # [수정] 점수 로직 전면 수정: 0점에서 시작
        score = 0

        # 1. 기본 품질 점수 (선명함, 밝음, 정면, 높은 신뢰도)
        if LIKELIHOOD_SCORE.get(face.blurred_likelihood, 0) < 3: score += 50
        if LIKELIHOOD_SCORE.get(face.under_exposed_likelihood, 0) < 3: score += 20
        if abs(face.roll_angle) < 20 and abs(face.pan_angle) < 20: score += 30
        if face.detection_confidence > 0.7: score += 20

        # 2. 우선순위 가산점 (P1 > P2 > P3)
        # [삭제] joy_score_val (API 기쁨) 관련 로직 모두 삭제

        # [수정] 랜드마크 기반 P1(웃음), P2(입다뭄) 점수 계산
        landmarks = {lm.type_: lm.position for lm in face.landmarks}
        mouth_openness = 0.0
        smile_pull = 0.0

        if (vision.FaceAnnotation.Landmark.Type.UPPER_LIP in landmarks and
            vision.FaceAnnotation.Landmark.Type.LOWER_LIP in landmarks):
            mouth_openness = abs(landmarks[vision.FaceAnnotation.Landmark.Type.UPPER_LIP].y -
                                 landmarks[vision.FaceAnnotation.Landmark.Type.LOWER_LIP].y)

        if (vision.FaceAnnotation.Landmark.Type.MOUTH_CENTER in landmarks and
            vision.FaceAnnotation.Landmark.Type.MOUTH_LEFT in landmarks and
            vision.FaceAnnotation.Landmark.Type.MOUTH_RIGHT in landmarks):
            center_y = landmarks[vision.FaceAnnotation.Landmark.Type.MOUTH_CENTER].y
            left_y = landmarks[vision.FaceAnnotation.Landmark.Type.MOUTH_LEFT].y
            right_y = landmarks[vision.FaceAnnotation.Landmark.Type.MOUTH_RIGHT].y
            # 입꼬리가 중앙보다 위로 올라갈수록 점수가 높음 (양수)
            smile_pull = (center_y - left_y) + (center_y - right_y)

        mouth_info_str = f"Open:{mouth_openness:.2f}, Pull:{smile_pull:.2f}"

        # [수정] 랜드마크만으로 P1/P2/P3 로직 통합
        # P1: 랜드마크가 '웃음'이라 함(pull>0.03)
        if smile_pull > 0.03:
            score += 150 # P1 (미소/웃음)
            if smile_pull > 0.1: # 활짝 웃음
                score += 150 # 추가 점수

        # P2: P1이 아닌 경우 중, 입을 다문 경우
        elif mouth_openness <= 0.1:
             score += 100 # P2 (입 다문 얼굴)

        # P3: P1, P2 모두 아닌 경우 (입 벌린 얼굴)
        # (가산점 없음. 기본 점수 120점 근처)

        if score > best_face_score:
            best_face_score = score
            best_mouth_info = mouth_info_str

    return best_face_score, "얼굴 있음", best_mouth_info


# --- 4. 메인 로직 실행 함수 (최적 썸네일 선정) ---
def find_best_thumbnail(video_path):
    """
    비디오를 분석하여 '베스트 썸네일' 1개를 선정합니다.
    """
    if 'vision_client' not in globals():
         print("❌ 오류: Vision AI 클라이언트가 준비되지 않았습니다.")
         return

    # [수정] 프레임 추출 간격을 0.25초로 세분화 (1초에 4장)
    frames = extract_frames_by_interval(video_path, sec_per_frame=0.25)
    if not frames:
        return

    print(f"\nGoogle Vision AI로 각 프레임 분석 시작 (총 {len(frames)}개)...")

    scored_frames = []

    # 2. 각 프레임을 Vision AI로 분석 및 점수화
    for i, frame_data in enumerate(frames):
        # [수정] joy_str 제거
        score, status, mouth_info_str = analyze_frame_for_thumbnail(frame_data['image_bytes'])
        frame_data['score'] = score
        frame_data['status'] = status
        frame_data['mouth'] = mouth_info_str
        scored_frames.append(frame_data)

        # [수정] 로그가 너무 많아지므로, 20프레임마다 한 번씩만 출력
        if i % 20 == 0: # 약 5초마다
            if status == "얼굴 있음":
                # [수정] 디버깅 로그 상세화 (API 기쁨 제거)
                print(f"  [시간: {frame_data['time_sec']:.2f}s] ✅ 얼굴 감지됨 (점수: {int(score)}) ({mouth_info_str})")
            else:
                print(f"  [시간: {frame_data['time_sec']:.2f}s] 얼굴 없음 (점수: {int(score)})")

    scored_frames.sort(key=lambda x: x['score'], reverse=True)

    print("\n" + "="*30)
    print("🎉 AI 분석 완료! (최적 썸네일)")
    print("="*30)

    # [디버깅] 상위 5개 프레임 점수 출력
    print("--- 상위 5개 프레임 점수 ---")
    for i in range(min(5, len(scored_frames))):
        frame = scored_frames[i]
        # [수정] API 기쁨 제거
        print(f"  Top {i+1}: [시간: {frame['time_sec']:.2f}s] (점수: {int(frame['score'])}) ({frame['mouth']})")

    best_thumbnail = scored_frames[0]

    if best_thumbnail['score'] <= 0:
        print("\n결과: 🌄 이 영상에는 유의미한 얼굴이 없습니다.")
        print("      (우선순위 3) 영상의 50% 지점 프레임을 랜덤 썸네일로 지정합니다.")
        middle_frame = frames[len(frames) // 2]
        best_thumbnail = middle_frame
    else:
        print(f"\n결과: 😃 AI가 '베스트 썸네일'을 선정했습니다! (점수: {int(best_thumbnail['score'])})")

    print("\n--- [최종 결과] AI 자동 지정 썸네일 (Best Pick) ---")
    print(f"(선정 시간: {best_thumbnail['time_sec']:.2f}초)")
    cv2_imshow(best_thumbnail['image_cv2'])

#@title 5. 테스트 실행
# (Vision API가 활성화된 상태에서 이 셀을 실행합니다)
my_video_path = "/content/drive/MyDrive/video/thumbnail.MOV"

if 'PROJECT_ID' in globals() and PROJECT_ID:
    if os.path.exists(my_video_path):
        find_best_thumbnail(my_video_path)
    else:
        print(f"❌ 오류: 테스트할 영상 파일을 찾을 수 없습니다.")
        print(f"  -> 경로를 확인하세요: {my_video_path}")
else:
    print("❌ 오류: '#@title 4' 셀에 본인의 Google Cloud 프로젝트 ID를 입력하세요.")