# -*- coding: utf-8 -*-
"""얼굴정렬성능평가.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSgC_rXc_pFk2nHcMa-RMFziOj14yxzi
"""

#@title 1. 라이브러리 설치 (첫 1회만 실행)#@title 1. 라이브러리 설치 (첫 1회만 실행)
!pip install opencv-python-headless mediapipe ipywidgets

#@title 2. 한글 폰트 설치 (첫 1회만 실행)
!sudo apt-get install -y fonts-nanum*

#@title 3. Google Drive 마운트
from google.colab import drive
import os
drive.mount('/content/drive')
print("\n✅ Google Drive가 '/content/drive'에 마운트되었습니다.")

#@title 4. 가이드 음성 파일 경로 설정
# [!!!] 4개의 MP3 파일(perfect, not_found, all_in, move_back)이 들어있는 경로 입력
audio_folder_path = "/content/drive/MyDrive/audio" # 4개의 신규 음성 파일이 있는 경로

# [수정] 파일 경로 확인 (4개 파일 확인)
required_files = ["perfect.mp3", "not_found.mp3", "all_in.mp3", "move_back.mp3"]
missing_files = []
if not os.path.isdir(audio_folder_path):
    print(f"⚠️ 경고: '{audio_folder_path}'는 유효한 폴더가 아닙니다.")
else:
    for f in required_files:
        if not os.path.exists(os.path.join(audio_folder_path, f)):
            missing_files.append(f)

if not missing_files:
    print("\n✅ 모든 음성 파일 경로 확인 완료.")
else:
    print(f"\n⚠️ 경고: {audio_folder_path} 폴더 누락 파일: {missing_files}")

#@title 5. [A코드] 비디오 파일 + 분리된 오디오로 얼굴 정렬 실행

import cv2
import mediapipe as mp
import numpy as np
from google.colab.patches import cv2_imshow
# [수정] 오디오 재생을 위한 라이브러리 임포트
from IPython.display import display, Javascript, Audio
from IPython.display import clear_output
from ipywidgets import Output # [수정] google.colab이 아닌 ipywidgets에서 임포트
import base64
from PIL import ImageFont, ImageDraw, Image
import time
import json
import os

# --- 0. [신규] 오디오 재생을 위한 별도 출력 셀 생성 ---
# 비디오(cv2_imshow)와 오디오(display)의 충돌을 막기 위해 셀을 분리
audio_output = Output()
print("오디오 출력 셀이 준비되었습니다.")

# --- 1. 한글 폰트 설정 ---
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
try:
    font = ImageFont.truetype(font_path, 24)
except IOError:
    print(f"폰트를 로드할 수 없습니다: {font_path}")
    font = ImageFont.load_default()

# --- 2. MediaPipe Face Mesh 초기화 ---
mp_face_mesh = mp.solutions.face_mesh
face_mesh = mp_face_mesh.FaceMesh(
    max_num_faces=5, # 최대 5명까지 인식
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5)

# --- 3. 자동 프레이밍 로직 (핵심) ---
global_guide_state = ""
last_audio_play_time = 0
face_not_visible_counter = 0
FACE_NOT_VISIBLE_THRESHOLD = 10 # 약 1/3초

def check_auto_framing(multi_face_landmarks, frame_width, frame_height):
    global global_guide_state, last_audio_play_time, face_not_visible_counter

    message = ""
    new_state = ""
    is_well_framed = False
    face_detected = bool(multi_face_landmarks)

    if face_detected:
        all_x, all_y = [], []
        for face_landmarks in multi_face_landmarks:
            for lm in face_landmarks.landmark:
                all_x.append(lm.x)
                all_y.append(lm.y)

        min_x, max_x = min(all_x), max(all_x)
        min_y, max_y = min(all_y), max(all_y)
        box_width, box_height = max_x - min_x, max_y - min_y
        is_mostly_visible = (min_x > 0.05 and max_x < 0.95 and min_y > 0.05 and max_y < 0.95)

        if is_mostly_visible:
            face_not_visible_counter = 0
            TARGET_WIDTH_RATIO, TARGET_HEIGHT_RATIO = 0.8, 0.8

            if box_width > TARGET_WIDTH_RATIO or box_height > TARGET_HEIGHT_RATIO:
                message = "조금 뒤로 물러나세요"
                new_state = "move_back"
            else:
                message = "완벽합니다!"
                new_state = "perfect"
                is_well_framed = True
        else:
            face_not_visible_counter += 1
            if face_not_visible_counter >= FACE_NOT_VISIBLE_THRESHOLD:
                 message = "모든 분이 화면 안으로 들어오세요"
                 new_state = "all_in"
            else:
                 message = "모든 분이 화면 안으로 들어오세요"
                 new_state = global_guide_state
    else:
        face_not_visible_counter += 1
        if face_not_visible_counter >= FACE_NOT_VISIBLE_THRESHOLD:
            message = "얼굴을 찾을 수 없습니다"
            new_state = "not_found"
        else:
            message = "얼굴을 찾을 수 없습니다"
            new_state = global_guide_state

    # [수정] 음성 재생 로직 (IPython.display.Audio 사용)
    current_time = time.time()
    # "perfect"가 아니면서 상태 변경 시 (2초 딜레이)
    if new_state and new_state != "perfect" and new_state != global_guide_state and (current_time - last_audio_play_time > 2):
        global_guide_state = new_state
        last_audio_play_time = current_time
        try:
            # Google Drive 경로에서 MP3 파일 경로 생성
            audio_file_path = os.path.join(audio_folder_path, f"{new_state}.mp3")
            if os.path.exists(audio_file_path):
                # 별도의 오디오 출력 셀에서 재생
                with audio_output:
                    clear_output(wait=True) # 이전 오디오 위젯 삭제
                    display(Audio(audio_file_path, autoplay=True)) # 새 오디오 재생
            else:
                print(f"경고: {audio_file_path} 파일을 찾을 수 없습니다.")
        except Exception as e:
            print(f"오디오 재생 오류: {e}")

    elif new_state == "perfect":
        # "perfect" 상태일 때는 (소리 없이) 기존 소리만 끔
        if global_guide_state != "perfect":
            with audio_output:
                 clear_output(wait=True) # 기존 소리 정지
        global_guide_state = "perfect"

    return message, is_well_framed

# --- 4. [수정] 메인 실행 루프 (비디오 파일) ---

# [!!!] Google Drive에 있는 본인의 테스트 영상 파일 경로를 입력하세요
# --------------------------------------------------
my_video_path = "/content/drive/MyDrive/video/test.mov"
# --------------------------------------------------

print(f"'{my_video_path}' 파일을 열어 분석을 시작합니다...")

if not required_files:
     print("❌ 오류: 오디오 파일이 준비되지 않았습니다. '#@title 4' 셀을 확인하고 다시 실행하세요.")
else:
    # 1. 비디오 캡처 객체 생성
    cap = cv2.VideoCapture(my_video_path)
    if not cap.isOpened():
        print(f"❌ 오류: 비디오 파일을 열 수 없습니다. 경로를 확인하세요: {my_video_path}")
        print("   (참고: .mov 파일은 코덱 문제로 Colab에서 열리지 않을 수 있습니다. .mp4로 변환하는 것을 권장합니다.)")
    else:
        fps = cap.get(cv2.CAP_PROP_FPS)
        if fps == 0: fps = 30
        delay = 1 / fps
        print(f"영상 FPS: {fps:.2f} (프레임 딜레이: {delay:.3f}초)")

        # [신규] 비디오와 분리된 오디오 출력 셀을 표시
        display(audio_output)
        print("--- 비디오 분석 시작 (오디오는 위 셀에서 재생됩니다) ---")

        # [신규] 성능 측정용 변수
        total_frames_processed = 0
        total_processing_time = 0

        try:
            while cap.isOpened():
                ret, frame = cap.read()
                if not ret:
                    print("\n비디오 재생이 완료되었습니다.")
                    break

                # [성능 측정 시작]
                start_time = time.time()

                image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                results = face_mesh.process(image_rgb)
                frame_height, frame_width, _ = frame.shape

                # [수정] 거울 모드(flip)가 아니므로 정방향 안내 로직 필요
                # (check_auto_framing에서 이미 num_faces > 1 로직으로 처리됨)
                message, is_well_framed = check_auto_framing(results.multi_face_landmarks, frame_width, frame_height)

                # [성능 측정 종료]
                duration = time.time() - start_time
                total_processing_time += duration
                total_frames_processed += 1

                # 한글 텍스트 그리기
                cv2.rectangle(frame, (0, 0), (frame_width, 40), (0, 0, 0), -1)
                frame_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
                draw = ImageDraw.Draw(frame_pil)

                text_color = (0, 255, 0) if is_well_framed else (255, 255, 255)
                draw.text((10, 5), message, font=font, fill=text_color)

                frame = cv2.cvtColor(np.array(frame_pil), cv2.COLOR_RGB2BGR)

                # 비디오 프레임 출력
                cv2_imshow(frame)

                # 실시간 재생을 위해 FPS만큼 딜레이
                time.sleep(delay)

        except KeyboardInterrupt:
            print("비디오 재생을 중지합니다.")
        except Exception as e:
            print(f"예상치 못한 오류 발생: {e}")
        finally:
            cap.release()
            print("비디오 리소스를 해제했습니다.")

            # [신규] 최종 성능 리포트
            if total_frames_processed > 0:
                avg_time_ms = (total_processing_time / total_frames_processed) * 1000
                avg_fps = 1.0 / (total_processing_time / total_frames_processed)

                print("\n\n" + "="*50)
                print("🎉 MediaPipe (A코드) 성능 평가 완료")
                print("="*50)
                print(f"  총 분석 프레임 수: {total_frames_processed}개")
                print("\n--- 1. 속도 (FPS) ---")
                print(f"  총 처리 시간: {total_processing_time:.2f}초")
                print(f"  프레임 1개당 평균 처리 시간: {avg_time_ms:.2f} ms")
                print(f"  [평균 FPS (초당 프레임 수)]: {avg_fps:.2f} FPS")
            else:
                print("\n성능 평가 실패: 처리된 프레임이 없습니다.")